name: Crawler CD

on:
  push:
    branches:
      - develop
    paths:
      - 'crawler/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i $SERVER_KEY $SERVER_USER@$SERVER_IP "cd /home/ubuntu/Team-ED-fall && git pull origin develop"
